apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: klingon-cloaking-device-auth-netpol
  namespace: klingon-cloaking-device
spec:
  podSelector:
    matchLabels:
      app: klingon-cloaking-device
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 168.63.129.16/32
        - ipBlock:
            cidr: 10.224.0.0/16
      ports:
        - port: 9001
          protocol: TCP
