# Update these values before applying
apiVersion: v1
kind: Secret
metadata:
  name: klingon-cloaking-device-credentials
  namespace: klingon-cloaking-device
type: Opaque
stringData:
  kcd-knock-password: "<YOUR_KNOCK_PASSWORD>"
  kcd-access-password: "<YOUR_ACCESS_PASSWORD>"
