{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-keyvault
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.secretProvider.clientID | quote }}
    keyvaultName: {{ .Values.secretProvider.keyvaultName | quote }}
    tenantId: {{ .Values.secretProvider.tenantID | quote }}
    objects: |
      array:
        - |
          objectName: kcd-knock-password
          objectType: secret
        - |
          objectName: kcd-access-password
          objectType: secret
        - |
          objectName: kcd-tls-cert
          objectType: secret
        - |
          objectName: kcd-tls-key
          objectType: secret
  secretObjects:
    - secretName: {{ .Chart.Name }}-credentials
      type: Opaque
      data:
        - objectName: kcd-knock-password
          key: kcd-knock-password
        - objectName: kcd-access-password
          key: kcd-access-password
{{- end }}
