{{- if and (not .Values.secrets.existingSecret) (or .Values.secrets.knockPassword .Values.secrets.accessPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-credentials
  namespace: {{ include "kcd.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  kcd-knock-password: {{ .Values.secrets.knockPassword | quote }}
  kcd-access-password: {{ .Values.secrets.accessPassword | quote }}
{{- end }}
