apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ include "kcd.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- $annotations := .Values.serviceAccount.annotations | default dict }}
  {{- if .Values.azureWorkloadIdentity.clientId }}
  {{- $_ := set $annotations "azure.workload.identity/client-id" .Values.azureWorkloadIdentity.clientId }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
