{{- if eq .Values.tls.mode "inline" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls
  namespace: {{ include "kcd.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.inline.crt | quote }}
  tls.key: {{ .Values.tls.inline.key | quote }}
{{- end }}
